name: CS236FP
channels:
    - pytorch
    - nvidia
    - pyg
    - anaconda
    - conda-forge
dependencies:
    - python >= 3.0
    - pytorch
    - torchvision
    - torchaudio
    - pytorch-cuda=11.8
    - pyg
    - pandas
    - git
    - numpy
    - scipy
    - scikit-learn
    - tensorboard
    - biopython
    - pip
    - biopython
    - pip:
        - rna-tools
        - rmsd
        - packaging
